# Generated by Django 5.2.16 on 2026-07-22 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('designer_or_creator', models.CharField(default='Unknown', max_length=200)),
                ('year_created', models.IntegerField(blank=True, null=True)),
                ('year_banned', models.IntegerField(blank=True, null=True)),
                ('ban_category', models.CharField(choices=[('POLITICAL', 'Political Censorship'), ('ETHICAL', 'Ethical / Dark Patterns'), ('CULTURAL', 'Cultural Taboo'), ('SAFETY', 'Safety & Regulation'), ('OTHER', 'Other')], default='POLITICAL', max_length=20)),
                ('summary', models.TextField(help_text='Short teaser for cards')),
                ('full_story', models.TextField(help_text='Detailed story of the design and its ban')),
                ('primary_image', models.ImageField(upload_to='exhibits/primary/')),
                ('historical_context', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='galleries.gallery')),
            ],
            options={
                'ordering': ['-year_banned', '-created_at'],
            },
        ),
    ]
